### ISSUE TITLE
About the parameters in Table 3

### ISSUE THREAD

**Issue by BlacknoSheep** [grypesc/SEED#1]
In Table 3, it is shown that SEED utilizes 3.2 million parameters, whereas ResNet18 has 11.7 million parameters. Could you clarify which part of the parameters is referred to by "#Params." in the table?

**Comment by grypesc** [comment]
Hello, thanks for interest in this work.
As stated in Appendix A.1, we utilize ResNet32 for Tab.3 which has ~0.46M parameters. Then, you can calculate the number of total parameters (network weights and Gausses) using Eq. 3 in Appendix A.3. Hope that helps!

**Comment by BlacknoSheep** [comment]
> Hello, thanks for interest in this work. As stated in Appendix A.1, we utilize ResNet32 for Tab.3 which has ~0.46M parameters. Then, you can calculate the number of total parameters (network weights and Gausses) using Eq. 3 in Appendix A.3. Hope that helps!

Thanks!
