### ISSUE TITLE
Can not import an module

### ISSUE THREAD

**Issue by kandeldeepak46** [grypesc/SEED#3]
This is a very naive issue.

I cloned the repo, installed the dependencies, and tried the script 

_sh cifar10x10.sh_

I am getting the following error

![image](https://github.com/grypesc/SEED/assets/33603333/6963afd8-2cf0-4d24-a625-9023123966c0)

This is a very basic issue, I have verified that everything is there. I have no clue

**Comment by kandeldeepak46** [comment]
I have just tried a random hack : _added __init__.py inside the datasets_ folder and it worked

**Comment by grypesc** [comment]
Hey! The script should be run from the root directory, also try using bash, instead of sh and Python at least 3.7. Hope that helps!
